[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = 
    -v
    --strict-markers
    --tb=short
    --alluredir=allure-results
    --clean-alluredir
    --log-cli-level=INFO

markers =
    smoke: 冒烟测试
    regression: 回归测试
    slow: 慢速测试
